services:
  backend:
    build: .
    container_name: taskmanager-backend
    ports:
      - "5001:5000"
    environment:
      - SUPABASE_URL=https://bfxwtonlugfqwyorlzaw.supabase.co
      - SUPABASE_KEY=sb_publishable_dg7y4oy6-BqVJFK8vQI_lQ_zrGEWbjD
      - SECRET_KEY=task_manager_secret_key_12345
    restart: unless-stopped
